2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_setup.py:_flush():67] Configure stats pid to 43799
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_setup.py:_flush():67] Loading settings from /home/dextrolaev/.config/wandb/settings
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_setup.py:_flush():67] Loading settings from /home/dextrolaev/Desktop/DL/da6401_assignment1/wandb/settings
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/dextrolaev/Desktop/DL/da6401_assignment1/wandb/run-20250309_120901-jq1gkris/logs/debug.log
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/dextrolaev/Desktop/DL/da6401_assignment1/wandb/run-20250309_120901-jq1gkris/logs/debug-internal.log
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x77007a0ef410>
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():761] calling init triggers
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 16, 'epochs': 10, 'hidden_layer_size': [128, 64, 32, 10], 'learning_rate': 0.0006, 'num_of_hidden_layers': 4, 'optimizer': 'momentum', 'weight_initialization': 'xavier'}
config: {'_wandb': {}}
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():784] starting backend
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():788] sending inform_init request
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-09 12:09:01,771 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():798] backend started and connected
2025-03-09 12:09:01,772 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 16, 'epochs': 10, 'hidden_layer_size': [128, 64, 32, 10], 'learning_rate': 0.0006, 'num_of_hidden_layers': 4, 'optimizer': 'momentum', 'weight_initialization': 'xavier'}
2025-03-09 12:09:01,772 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 12:09:01,774 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():891] updated telemetry
2025-03-09 12:09:01,787 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 12:09:03,681 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 12:09:03,798 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 12:09:03,799 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 12:09:03,799 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 12:09:03,799 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 12:09:03,799 INFO    Thread-142 (_run_job):43799 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 12:13:45,182 INFO    MainThread:43799 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 12:13:45,183 INFO    MainThread:43799 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-09 12:13:49,721 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_finish():2112] finishing run cs24s031-indian-institute-of-technology-madras/dl-assignment1/jq1gkris
2025-03-09 12:13:49,721 INFO    Thread-142 (_run_job):43799 [jupyter.py:save_history():458] not saving jupyter history
2025-03-09 12:13:49,721 INFO    Thread-142 (_run_job):43799 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 12:13:49,721 INFO    Thread-142 (_run_job):43799 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 12:13:49,721 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 12:13:49,721 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_restore():2322] restore
2025-03-09 12:13:49,722 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_restore():2328] restore done
2025-03-09 12:13:49,722 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_restore():2322] restore
2025-03-09 12:13:49,722 INFO    Thread-142 (_run_job):43799 [wandb_run.py:_restore():2328] restore done
2025-03-09 12:13:49,722 ERROR   Thread-142 (_run_job):43799 [wandb_run.py:_atexit_cleanup():2361] Problem finishing run
Traceback (most recent call last):
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/ipykernel_43799/1025322279.py", line 17, in train
    nn.train(
  File "/tmp/ipykernel_43799/1111212547.py", line 152, in train
    sys.stdout.write(f"\rEpoch {ep + 1}/{epochs} - Batch {batch + 1}/{num_batches} - Loss: {train_loss / ((batch+1)*batch_size):.6f} Train-Acc: {train_acc / ((batch+1)*batch_size):.6f} val-loss:{val_loss:.6f} val-Acc: {val_acc:.6f} ")
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/wandb/sdk/lib/console_capture.py", line 147, in write_with_callbacks
    n = orig_write(s)
        ^^^^^^^^^^^^^
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/iostream.py", line 694, in write
    self._schedule_flush()
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/iostream.py", line 590, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/zmq/sugar/socket.py", line 707, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1092, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1134, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1209, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2352, in _atexit_cleanup
    self._on_finish()
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2604, in _on_finish
    with progress.progress_printer(
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/wandb/sdk/lib/progress.py", line 92, in progress_printer
    with printer.dynamic_text() as text_area:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/wandb/sdk/lib/printer.py", line 436, in dynamic_text
    handle = self._ipython_display.display(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/IPython/core/display_functions.py", line 285, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/IPython/core/display_functions.py", line 73, in publish_display_data
    display_pub.publish(
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 103, in publish
    self._flush_streams()
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 66, in _flush_streams
    sys.stdout.flush()
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home/dextrolaev/myenv/lib/python3.12/site-packages/zmq/sugar/socket.py", line 707, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1092, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1134, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1209, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
